### ISSUE TITLE
Possible problem with grading classes

### ISSUE THREAD

**Issue by kamilszczesny** [Zamenhof/api#3]
on 6th of August.
There were couple of classes scheduled. All of them are reported to be graded by teacher.
But attendance report shows 2 alerting facts:

1. One of the classes is marked as not graded although teacher states differently.
2. 2 classes seem to be inconsistent as part of learners are graded and part not.

It's all marked on following screenshoot - graded and unrated students and inconsistency.

![zamenhof-grading-problem](https://user-images.githubusercontent.com/1933153/43765557-7e733894-9a30-11e8-96b9-409025360db1.jpg)

**Comment by patzamgit** [comment]
It looks like the student assessment form was submitted multiple times. We will fix that with an **Edit** button.

There are two missing elements that would help us in reviewing the assessment grades system: 
On the school administrator account / attendance page:
1. a **group ID** column on the attendance page. 
2. a **grades** column with access to the grades.

**Comment by patzamgit** [comment]
I transferred this post to the **working** column because we need to bring additional improvements. 
The initial solution with the "Edit" button did not work as expected.
 
**New solution:** 
On the **student assessment** tab, we will add a **Send** button. The teacher will be able to use the **Save** button multiple times and the **Send** button will be final. 

The xAPI data will be sent only when the teacher will use the **Send** button.

**Comment by patzamgit** [comment]
From the attendance report, check the **Group** view to see the data we collected from the **Grades** form on the teacher call-box.
We also adjusted the Grades form UI to make sure the teachers are saving the data.
